### PR TITLE
Allow installation to file

### PR DESCRIPTION
**Pull request by liamdawson**
Adds a --mount-file flag to mount a disk image and use it as the device.

### Why?

I'm trying out a k3os cluster in libvirt, and it's simpler to orchestrate the install process if I can do it directly to a libvirt volume, instead of organising the installation inside the VM.

I manually did this mounting/unmounting myself in the script I wrote, but figured it might be useful to others!

### Usage

```shell
$ virsh vol-create-as --pool default --name k3os-machine --capacity 8G --format raw
Vol k3os-machine created
$ ./install.sh --mount-file "$(virsh vol-path --pool default --vol k3os-machine)" /media/cygnus/var/libvirt/reference/k3os-iso
...
$ file "$(virsh vol-path --pool default --vol k3os-machine)"
/var/lib/libvirt/images/k3os-machine: DOS/MBR boot sector; partition 1 : ID=0xee, start-CHS (0x0,0,1), end-CHS (0x3ff,254,63), startsector 1, 16777215 sectors, extended partition table (last)
$ parted "$(virsh vol-path --pool default --vol k3os-machine)"
GNU Parted 3.2
Using /var/lib/libvirt/images/k3os-machine
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) print
Model:  (file)
Disk /var/lib/libvirt/images/k3os-machine: 8590MB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags:

Number  Start   End     Size    File system  Name     Flags
 1      1049kB  50.3MB  49.3MB  fat32        primary  boot, esp
 2      50.3MB  550MB   500MB   ext4         primary
```

### Thoughts

I could see that this would be an extra bit of maintenance—I could alternatively take this logic and build a separate tool that acts as a higher-order layer? I figure it's more likely to be kept up to date here, though, especially if I don't continue using k3os after my evaluation.

This might also act as a workaround for https://github.com/rancher/k3os/issues/133, that's actually my use-case! 🙂

### CODE REVIEW

**Comment by dweomer** [comment]
@liamdawson I see a problem with this in that it is better solved by first mounting the disk file created with `virsh vol-create-as ...` on a loopback device (as you do in this PR) and then pass that device to `install.sh`. Additionally, you will likely need to post-process the mounted disk to correctly name the device it will be running from within the VM as `install.sh` assumes it is run within the context of the machine that will be booting (e.g. /dev/loop0 -> /dev/vda2). You can know this is problematic if you inspect your installed disk for `/k3os/system/growpart` and the first entry is not a device that your VM will see.

**Comment by liamdawson** [comment]
Right. So would it be better to create a different script entirely to account for the differences? Would that be accepted in this repo?

**Comment by dweomer** [comment]
> Right. So would it be better to create a different script entirely to account for the differences? Would that be accepted in this repo?

Sure, it could fit under package/virsh perhaps?

**Comment by liamdawson** [comment]
It's going to be a while before I really get to this, so if someone else would like to take over, you're welcome to do so.

**Comment by dweomer** [comment]
@liamdawson (or anyone interested) please re-open when you get the chance to work on this

**Pull request closed without merging**
