### PR TITLE
add manifest fetching

### PR DESCRIPTION
**Pull request by Eriner**
This is much more convenient than using "write_files".

### CODE REVIEW

**Comment by phaer** [comment]
I think that's a nice suggestion, but I am currently using `write_files` to add bash completions and some custom aliases to my k3os nodes, e.g.:

```
    write_files: [{
        owner: "root:root"
        path: "/etc/profile.d/zz-bashrc.sh"
        permissions: "0644"
        content: """
        source <(kubectl completion bash)
        alias Pods="kubectl get pods --all-namespaces"
        [...]
        """
  }]
```

This would not be supported anymore with your suggested change, right? Maybe both could be supported? Or would there be interest to add an extra cloud init attribute for shell config snippets?

**Comment by Eriner** [comment]
@phaer This change doesn't remove support for `write_files`.

**Comment by phaer** [comment]
Oh right, I guess I misinterpreted based on the first documentation change and the PR description. Thanks for the hint and sorry for the noise! :)

**Comment by knksmith57** [comment]
big +1, this would be super useful and simplify current `*_cmd` workarounds. thanks for the contribution!

1 suggestion: allow for handling of conflicting manifest names. Operators frequently have no control over the remote filename and the proposed implementation affords no facility to handle this case.

thanks again!

**Pull request closed without merging**
