### PR TITLE
Add rng-tools

### PR DESCRIPTION
**Pull request by zimme**
Use hw rng devices for entropy if found.

### CODE REVIEW

**Comment by zimme** [comment]
Not completely sure if this will conflict with haveged in any way.

**Comment by dweomer** [comment]
@zimme you probably want to also add `rng-tools-openrc` and modify the [overlay/libexec/boot](https://github.com/rancher/k3os/blob/8f83e0e0abffeb23c18906541b4f460d657f84fa/overlay/libexec/k3os/boot#L34) script to use `rngd` instead of `haveged`.

is it your intention to replace `haveged` with `rngd` or just have both present? they both provide the same `entropy` openrc service.

**Comment by zimme** [comment]
The intention was to use rng-tools for devices that have hardware rng devices like the rpi's from rpi2 or 3 and above. And for devices or vms that don't have hw rng use haveged instead.

**Comment by zimme** [comment]
From what I've read so far it seems as though rng-tools will setup and use `/dev/hwrandom` or `/dev/hwrng` if available and if it's not available do nothing. That leads me to believe once could use rng-tools and haveged together.

**Comment by dweomer** [comment]
Included with #292

**Pull request closed without merging**
