### PR TITLE
Update lite output to support arm64

### PR DESCRIPTION
**Pull request by miry**
Use same arch for lite image artifcats as in other places: arm64.
Because now lite conflicts with full rootfs, so add suffix lite to the
name.

In the page of latest release https://github.com/rancher/k3os/releases/tag/v0.2.1
you can see `k3os-rootfs-arm.tar.gz` and `k3os-rootfs-arm64.tar.gz`.
The `k3os-rootfs-arm64.tar.gz` is the full output, where `k3os-rootfs-arm.tar.gz` lite.

Also it fix issue to build only for `arm64` arch via: `export DAPPER_HOST_ARCH=arm64`
The lite version is skipped, because it expects `arm`.

Reproduce:

```shell
$ export DAPPER_HOST_ARCH=arm64
$ make ci
```

### CODE REVIEW

**Comment by zimme** [comment]
If I get the code correctly the `lite` vs `full` is if an iso and other files should be generated instead of just a rootfs file.

So this PR doesn't actually seem to fix anything.

**Comment by miry** [comment]
@zimme It fixes the problem to build lite rootfs with `export DAPPER_HOST_ARCH=arm64` and removes possible collision of full and lite builds.

**Comment by zimme** [comment]
Just to be clear here.

1. There isn't a lite or a full rootfs. There is only one kind of rootfs in this project from what I can tell.
2. At the latest state, if we're on `arm` then the build is only outputting the rootfs to the dist folder and for `arm64` and `amd64` it outputs the rootfs and and iso and some kernel files like `-vmlinuz` and `-initrd`.

One of the changes you have here would stop the rootfs being put into the dist folder when running the build for `arm` as you've replaced it with `arm64` and when running the build for `arm64` it would output the same rootfs for `arm64` in the dist folder using 2 different names.

But maybe I'm missing something?

**Comment by miry** [comment]
@zimme I used words base on https://github.com/rancher/k3os/tree/master/images/output. There are 2 output: `full` and `lite`. What is inside, it think is not important for now.
The problem is here that output is different from expected name and second you could not build everything for `arm64`, because lite folder have `arm` (I could not find any usage of it in other folders). It makes confusion.

If you choose Arch `arm`, as I remember correctly would build nothing, becuase it used in one place.

```
$ export DAPPER_HOST_ARCH=arm
$ make ci
```

**Comment by miry** [comment]
inactive project

**Pull request closed without merging**
